version: '3'

networks:
  app-net:
    driver: bridge

services:
  cass:
    image: cassandra:latest
    volumes:
      - cassandra:/data/
    ports:
      - "9042:9042"
    networks:
      - app-net

  api:
    build:
      context: .
      args:
        DB_HOST: cass
        DB_USER: cassandra
        DB_PASS: cassandra
    depends_on:
      - cass
    ports:
      - "5000:5000"
    networks:
      - app-net
    links:
      - cass

volumes:
  cassandra: